FROM openjdk:21-jdk

WORKDIR /app

# Copia os arquivos necessários
COPY generate-cert.sh /app/generate-cert.sh
COPY target/iobound-thread-app-0.0.1-SNAPSHOT.jar /app/app.jar

# Torna o script executável dentro do container
RUN chmod +x /app/generate-cert.sh

# Executa o script antes de iniciar a aplicação
RUN /app/generate-cert.sh

RUN ls /app

CMD ["java", \
    "-jar", \
    "-Dcom.sun.management.jmxremote.port=5001", \
    "-Dcom.sun.management.jmxremote.rmi.port=5001", \
    "-Dcom.sun.management.jmxremote.local.only=false", \
    "-Dcom.sun.management.jmxremote.authenticate=false", \
    "-Dcom.sun.management.jmxremote.ssl=false", \
    "-Djava.rmi.server.hostname=localhost", \
     "/app/app.jar"]
